version: 0.1.{build}
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-beta'
  assembly_version: '{version}'
  file_version: '{version}'
build_script:
  - cmd: dotnet build -c Release
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test -c Release --no-build Standard.Configuration.Alias.Test
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: NuGet
  api_key:
    secure: FSoixCDwYnyOba7fxlvt7uPkaPQUoqToF2mrzDCnQEAPBHvzgw+N7WYUfsxwTrFT
  skip_symbols: false
  artifact: /.*\.nupkg/