version: 0.1.{build}
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build Standard.Configuration.Alias -c Release
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test