version: 0.1.{build}-beta
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build -c Release
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: dotnet test -c Release --no-build Standard.Configuration.Alias.Test
deploy:
  provider: NuGet
  api_key:
    secure: FSoixCDwYnyOba7fxlvt7uPkaPQUoqToF2mrzDCnQEAPBHvzgw+N7WYUfsxwTrFT
  skip_symbols: false
  artifact: /.*\.nupkg/